<?php

declare(strict_types=1);

namespace Gamez\Mite\Tests\Integration\SimpleApi;

use Gamez\Mite\Tests\Integration\SimpleApiTestCase;
use ReflectionClass;

/**
 * @coversDefaultClass  \Gamez\Mite\SimpleApi
 *
 * @covers \Gamez\Mite\Api\HttpApiClient
 * @covers \Gamez\Mite\SimpleApi
 *
 * @internal
 */
final class CustomerTest extends SimpleApiTestCase
{
    /**
     * @var array<non-empty-string, mixed>
     */
    private static array $customer;

    public static function setUpBeforeClass(): void
    {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub

        self::$customer = self::$api->createCustomer([
            'name' => (new ReflectionClass(self::class))->getShortName(),
        ]);
    }

    public static function tearDownAfterClass(): void
    {
        self::$api->deleteCustomer(self::$customer['id']);
    }

    /**
     * @covers ::createCustomer
     * @covers ::deleteCustomer
     */
    public function testItCanBeCreatedAndDeleted(): void
    {
        $customer = self::$api->createCustomer(['name' => __FUNCTION__]);

        $this->assertCustomerStructure($customer);
        $this->assertSame(__FUNCTION__, $customer['name']);

        self::$api->deleteCustomer($customer['id']);
    }

    /**
     * @covers ::getCustomer
     */
    public function testItCanBeFetched(): void
    {
        $customer = self::$api->getCustomer(self::$customer['id']);

        $this->assertCustomerStructure($customer);
        $this->assertSame(self::$customer['id'], $customer['id']);
    }

    /**
     * @covers ::updateCustomer
     */
    public function testItCanBeUpdated(): void
    {
        $updated = self::$api->updateCustomer(self::$customer['id'], ['note' => __FUNCTION__]);

        $this->assertCustomerStructure($updated);
        $this->assertSame(__FUNCTION__, $updated['note']);
    }

    /**
     * @covers ::getActiveCustomers
     */
    public function testItProvidesAListOfActiveCustomers(): void
    {
        self::$api->updateCustomer(self::$customer['id'], ['archived' => false]);

        $customers = self::$api->getActiveCustomers();

        $this->assertGreaterThanOrEqual(1, $customers);

        $customerIds = array_column($customers, 'id');

        $this->assertContains(self::$customer['id'], $customerIds);
    }

    /**
     * @covers ::getArchivedCustomers
     */
    public function testItProvidesAListOfArchivedCustomers(): void
    {
        self::$api->updateCustomer(self::$customer['id'], ['archived' => true]);

        $customers = self::$api->getArchivedCustomers();

        $this->assertGreaterThanOrEqual(1, $customers);

        $customerIds = array_column($customers, 'id');

        $this->assertContains(self::$customer['id'], $customerIds);
    }
}
